book:
    title:            "Documentación de easybook"
    author:           "Javier Eguiluz"
    edition:          "Primera edición"
    language:         es
    publication_date: ~

    generator: { name: easybook, version: 5.0 }

    contents:
        - { element: cover }
        - { element: toc   }
        - { element: chapter, number: 1, content: chapter1.md }
        - { element: chapter, number: 2, content: chapter2.md }
        - { element: chapter, number: 3, content: chapter3.md }
        - { element: appendix, number: A, content: referencia.md }

    editions:
        ebook:
            format:          epub
            include_styles:  true
            highlight_cache: true
            highlight_code:  true
            labels:          ['appendix', 'chapter', 'figure']
            theme:           clean
            toc:
                deep:        1
                elements:    ["appendix", "chapter"]

        print:
            format:          pdf
            highlight_cache: true
            highlight_code:  true
            include_styles:  true
            isbn:            ~
            labels:          ['appendix', 'chapter', 'figure']
            margin:
                top:         25mm
                bottom:      25mm
                inner:       30mm
                outer:       20mm
            page_size:       A4
            theme:           clean
            toc:
                deep:        2
                elements:    ['appendix', 'chapter']
            two_sided:       true
            
        print-wkhtmltopdf:
            extends:        print
            pdf_engine:     wkhtmltopdf

        web:
            format:          html
            highlight_cache: true
            highlight_code:  true
            include_styles:  true
            labels:          ['appendix', 'chapter', 'figure']
            theme:           clean
            toc:
                deep:        2
                elements:    ['appendix', 'chapter']

        website:
            extends:         web
            format:          html_chunked
            chunk_level:     2
            images_base_dir: /img/doc-en/

        easybook-project.org:
            format:          html_chunked
            chunk_level:     2
            include_styles:  false
            highlight_cache: false
            highlight_code:  true
            images_base_dir: /img/doc-en/
            labels:          ['appendix', 'chapter', 'figure']
            theme:           clean
            toc:
                deep:        2
                elements:    ["appendix", "chapter"]

